package edu.sdust.moon.Enum;

public enum AffairsEventType {
    MESSAGEFRIENDRECALLEVENT,
    MESSAGEGROUPRECALLEVENT,
    MEMBERNUDGEDEVENT,
    BOTNUDGEDEVENT,
    BEFOREIMAGEUPLOADEVENT,
    IMAGEUPLOADSUCCEEDEVENT,
    IMAGEUPLOADFAILEDEVENT
}
