package edu.sdust.moon.Enum;

public enum BotEventType {
    BOTMUTEEVENT,
    BOTUNMUTEEVENT,
    BOTQUITGROUPEVENT,
    BOTKICKGROUPEVENT,
    BOTACTIVEJOINGROUPEVENT,

    BOTINVITEJOINGROUPEVENT,
    BOTINVITEDJOINGROUPREQUESTEVENT,
    BOTRETRIEVEJOINGROUPEVENT,
    BOTGROUPPERMISSIONCHANGEEVENT,

    BOTONLINEEVENT,
    BOTAVATARCHANGEDEVENT,
    BOTNICKCHANGEDEVENT,
    BOTRELOGINEVENT,
    BOTACTIVEOFFLINEEVENT,
    BOTFORCEOFFLINEEVENT,
    PACKETFACTORY10008,
    BOTDROPPEDOFFLINEEVENT,
    BOTREQUIRERECONNECTOFFLINEEVENT
}
