package edu.sdust.moon.Enum;

public enum FriendEventType {
    NEWFRIENDREQUESTEVENT,
    FRIENDADDEVENT,
    FRIENDDELETEEVENT,
    FRIENDMESSAGEEVENT,
    FRIENDINPUTSTATUSCHANGEDEVENT,
    FRIENDMESSAGEPOSTSENDEVENT,
    FRIENDMESSAGEPRESENDEVENT,

    FRIENDNICKCHANGEDEVENT,
    FRIENDREMARKCHANGEEVENT,
    FRIENDAVATARCHANGEDEVENT
}
