package edu.sdust.moon.Enum;

public enum GroupEventType {
    GROUPMESSAGEEVENT,
    GROUPMESSAGEPOSTSENDEVENT,
    GROUPMESSAGEPRESENDEVENT,

    GROUPALLOWANONYMOUSCHATEVENT,
    GROUPALLOWCONFESSTALKEVENT,
    GROUPALLOWMEMBERINVITEEVENT,
    GROUPENTRANCEANNOUNCEMENTCHANGEEVENT,

    GROUPNAMECHANGEEVENT,
    GROUPMUTEALLEVENT
}
