package edu.sdust.moon.Enum;

public enum MemberEventType {
    MEMBERJOINREQUESTEVENT, MEMBERINVITEJOINEVENT, MEMBERACTIVEJOINEVENT,
    MEMBERKICKEVENT, MEMBERQUITEVENT, MEMBERJOINRETRIEVEEVENT, BOTINVITEDJOINGROUPREQUESTEVENT,

    MEMBERCARDCHANGEEVENT, MEMBERSPECIALTITLECHANGEEVENT, MEMBERMUTEEVENT, MEMBERUNMUTEEVENT,
    MEMBERPERMISSIONCHANGEEVENT, TEMPMESSAGEPOSTSENDEVENT, TEMPMESSAGEPRESENDEVENT
}
